name: Build for Mac

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: macos-14
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run package
        run: yarn run package

      - name: Remove quarantine attributes
        run: xattr -c out/mulmocast-app-darwin-arm64/mulmocast-app.app
        
      - name: Upload generated media
        uses: actions/upload-artifact@v4
        with:
          name: bin-mac-${{ matrix.node-version }}
          path: out/
