name: CI for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        shell: powershell
        run: yarn install --frozen-lockfile

      - name: Run package
        shell: powershell
        run: yarn run package
        
      - name: Upload generated media
        uses: actions/upload-artifact@v4
        with:
          name: bin-win-${{ matrix.node-version }}
          path: out/
