name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check

      - name: Run ESLint
        run: yarn lint

      - name: Check Prettier formatting
        run: yarn format:check
        
      - name: Run test
        run: yarn test

      - name: Run package
        run: yarn run package
        
      - name: Upload generated media
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.node-version }}
          path: out/
